In [2]:
%matplotlib auto
import matplotlib.pyplot as plt
import cv2
import glob
import numpy as np
import pickle

Using matplotlib backend: <object object at 0x7f610c96cdd0>


In [23]:
images_folder = '/home/sykes/absluate_tracker/data/tracker_calibration_images/camera1/*'
images_names = sorted(glob.glob(images_folder))
images = []
for imname in images_names:
    im = cv.imread(imname, 1)
    images.append(im)    

chessboardSize = (5,8)
frameSize = (1920,1080)


In [25]:
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)


# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((chessboardSize[0] * chessboardSize[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:chessboardSize[0],0:chessboardSize[1]].T.reshape(-1,2)

size_of_chessboard_squares_mm = 50
objp = objp * size_of_chessboard_squares_mm

In [26]:
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
for img in images:

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, chessboardSize, None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        cv2.drawChessboardCorners(img, chessboardSize, corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(1000)


cv2.destroyAllWindows()

In [31]:
ret, cameraMatrix, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, frameSize, None, None)

In [3]:
image = cv2.imread('/home/sykes/absluate_tracker/data/tracker_calibration_images/camera1/image15.png')
b,g,image_r = cv2.split(image)
img = cv2.inRange(image_r,240,255)
contours, hierarchy = cv2.findContours(img,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)


for c in contours:
   # calculate moments for each contour
   M = cv2.moments(c)

   # calculate x,y coordinate of center
   cX = int(M["m10"] / M["m00"])
   cY = int(M["m01"] / M["m00"])
   print('centroid: X:{}, Y:{}'.format(cX, cY)) 
   cv2.circle(img, (cX, cY), 5, (255, 255, 255), -1)
   cv2.putText(img, "centroid", (cX -25, cY -25),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

   # display the image
   cv2.imshow("Image", img)
   cv2.waitKey(0)


centroid: X:743, Y:496


In [4]:
contours

(array([[[741, 492]],
 
        [[739, 494]],
 
        [[739, 498]],
 
        [[741, 500]],
 
        [[745, 500]],
 
        [[747, 498]],
 
        [[747, 494]],
 
        [[745, 492]]], dtype=int32),)

: 

In [3]:
file = open('/home/sykes/absluate_tracker/data/data.pickle', 'rb')
data = pickle.load(file)

In [4]:
data

[array([[977., 611.],
        [964., 594.],
        [936., 609.],
        [958., 627.]]),
 array([[ 843.,  513.],
        [ 815.,  702.],
        [1085.,  720.],
        [1092.,  527.]]),
 array([[ 686.,  618.],
        [ 973.,  834.],
        [1225.,  603.],
        [ 951.,  434.]]),
 array([[ 671.,  534.],
        [ 974.,  753.],
        [1240.,  519.],
        [ 951.,  350.]]),
 array([[ 801.,  452.],
        [ 842.,  647.],
        [1128.,  609.],
        [1064.,  421.]]),
 array([[ 896.,  519.],
        [ 953.,  569.],
        [1018.,  534.],
        [ 970.,  486.]]),
 array([[ 894.,  465.],
        [ 952.,  514.],
        [1020.,  479.],
        [ 970.,  431.]]),
 array([[ 951.,  427.],
        [ 895.,  474.],
        [ 962.,  519.],
        [1027.,  469.]]),
 array([[ 878.,  379.],
        [ 812.,  529.],
        [1046.,  577.],
        [1100.,  419.]]),
 array([[ 800.,  428.],
        [ 890.,  588.],
        [1123.,  519.],
        [1023.,  371.]]),
 array([[ 793.,  358.],
    